#ifndef GLVIEW_WIDGET_GLOBAL_H
#define GLVIEW_WIDGET_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GLVIEW_WIDGET_LIBRARY)
#  define GLVIEW_WIDGETSHARED_EXPORT Q_DECL_EXPORT
#else
#  define GLVIEW_WIDGETSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // GLVIEW_WIDGET_GLOBAL_H
